/* generated using openapi-typescript-codegen -- do not edit */
/* istanbul ignore file */
/* tslint:disable */
/* eslint-disable */
import type { Announcement } from './Announcement';
import type { EventKey } from './EventKey';
import type { Match } from './Match';
import type { PartsRequest } from './PartsRequest';
export type EventStatus = {
    eventKey?: EventKey;
    /**
     * The timestamp (Unix time in milliseconds) at which this event status snapshot was generated by Nexus.
     */
    dataAsOfTime?: number;
    /**
     * The human-friendly label for the latest match that is queuing. Null if the event is not currently queuing a match. Examples: `Practice 1`, `Qualification 24`, `Qualification 24 Replay`, `Playoff 8`, `Final 1`
     */
    nowQueuing?: string | null;
    /**
     * All scheduled matches for this event, sorted by play order (practice matches first, then qualifications, then playoffs). This array is empty if the event has not yet scheduled any matches. This array can include scheduled match replays which are indicated by the `replayOf` property.
     */
    matches?: Array<Match>;
    /**
     * Current announcements that are posted for this event. This array is empty if there are no current announcements.
     */
    announcements?: Array<Announcement>;
    /**
     * Current parts requests that are posted for this event. This array is empty if there are no current parts requests.
     */
    partsRequests?: Array<PartsRequest>;
};

