/* generated using openapi-typescript-codegen -- do not edit */
/* istanbul ignore file */
/* tslint:disable */
/* eslint-disable */
import type { EventKey } from './EventKey';
import type { Match } from './Match';
export type MatchStatus = {
    eventKey?: EventKey;
    /**
     * The timestamp (Unix time in milliseconds) at which this event status snapshot was generated by Nexus.
     */
    dataAsOfTime?: number;
    /**
     * The updated match.
     */
    match?: Match;
};

